### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by joshuaballoch** [svicalifornia/skim#34]
@jfirebaugh this is a really cool project, and I'm considering using it in a site I am working on. 

Is it still being developed/maintained? Are there any caveats that you would mention in considering this for a production site?

Sorry if this is not the place for a question like this, please let me know if there is a better place. And again, cool project! thanks.

**Comment by 0-1-0** [comment]
+1 for Rails 4.2 support.

**Comment by gkopylov** [comment]
I update some dependency gems for supporting rails 4.2 and slim 3.
Everything works fine in my project(which use rails 4.2 and slim 3), but there are some failing tests (6 of 129) that need to be fixed(it is 6 tests which use functions defined in test/context.coffee and I can not understand why it is failing). So if you can fix them you can push it my branch https://github.com/gkopylov/skim/tree/upgrade_for_rails_4_2_and_slim_3 and this fix will added to PR https://github.com/jfirebaugh/skim/pull/39

**Comment by gkopylov** [comment]
I have corrected the rest of other tests, but it seems there are some problems with multiline or with template compilation in a block. All tests are passed though.

**Comment by jfirebaugh** [comment]
So, as you might have noticed, I don't have time or inclination to maintain this to the level it deserves. @gkopylov or others on this thread, would you be interested in taking over? I would transfer the repository and rubygem ownership to you.

**Comment by gkopylov** [comment]
Maybe it would be better to create organization (for example "skim") on github, move this project to the organization and invite people there, so this project will be more independent of someone specific person.

**Comment by jfirebaugh** [comment]
I'd actually rather transfer it to an individual. I suspect that it will continue to languish unless there's somebody specific who wants to accept ownership.

**Comment by svicalifornia** [comment]
@jfirebaugh I'm interested in maintaining the skim gem and repo. Please get in touch with me.

**Comment by svicalifornia** [comment]
Hi everyone, I have just become the maintainer of this project. In addition to Slim and CoffeeScript fixes, I have some additional features planned, including using Skim with React and other frameworks. I'll also be promoting Skim and CoffeeScript to try to build the community. It should be an exciting time for us!

To answer the original question by @joshuaballoch, I have used and continue to use Skim in production, and it has worked pretty well. There are known issues, such as some CoffeeScript expressions not working properly, and some attribute values not merging as expected, which I intend to fix. Overall, you should expect Skim to keep improving and becoming a top solution for client-side templating.

I'm closing this question for now. If you encounter specific bugs or other problems, or would like to request a feature, please open new issues on this GitHub repo.

**Comment by gkopylov** [comment]
@svicalifornia what kind of integration will you plan for Skim with React? Could you describe your plans with more details? And yeah, good luck! :+1:

**Comment by svicalifornia** [comment]
I have a branch in development that will (optionally) return a hierarchy of React elements instead of HTML when calling a Skim template function. It's working great for me so far, but I'm still working on test coverage.
